export const generalQuestions = [
    {
        question: "How do I receive the item?",
        answer: "If the item is nearby you, you can choose local pick-up during the borrow process on the app. If local pick-up is not possible, you can choose shipping. The prepaid shipping labels will be automatically generated by Canada Post in the checkout process in the app. ",
    },
    {
        question: "How much is shipping?",
        answer: "This is dependent on factors such as price of the item and distance. Simply click borrow on the item you’re interested in to see the cost of shipping. Prepaid shipping labels are automatically generated in the app through Canada Post.",
    },
    {
        question: "Who is responsible for paying shipping?",
        answer: "If an item’s borrow cost is over $50, lenders and borrowers split the cost of shipping. If the item is under $50, borrowers pay both ways. This is automatically deducted during the checkout process in the app and prepaid shipping labels will be generated.",
    },
    {
        question: "What are the fees for using rax?",
        answer: "rax is free to use! We just take a commission of 20% from lenders. ",
    },
    {
        question: "Who is responsible for cleaning the item?",
        answer: "Lenders are responsible for cleaning the item upon return from the borrower. ",
    },
    {
        question: "How do I get help from rax or raise a ticket?",
        answer: "Go to the “chat” section of the app and send a message to rax.",
    },
];

export const borrowerQuestions = [
    {
        question: "I’m borrowing an item for an event, how do I know it will come in time? Can I reserve an item for an event that is months away?",
        type: 'list',
        answer: {
            lists: ["If you are borrowing an item for a specific date, choose your event date in the app.",
                "If you are doing local in-person pick-up,  you will pick-up the item on day 1 and return on the last day of your rental period. ",
                "If you are doing shipping, choose the borrow period of 10 days with the event date being on day 8. Your lender will ship out the item on day 1 and it will arrive on day 1 - 7. Wear your item on day 8 and ship it back on day 9 or 10. If you need a longer period, simply adjust the borrow period",
            ], text: "You may reserve your item 90 days in advance in the app - the earlier the better to ensure the item is free. You will not receive the item or you will not meet in person until day 1 of your borrow period.",
        },
    },
    {
        question: "I’m borrowing items for a vacation, what borrow period should I choose?",
        answer: "Choose a borrow period from 4 days (if local pick-up only), 10 days, 20 days, 1 month, 2 months, 3 months, 6 months. If doing local pick up, you will receive your item on day 1 and return on the last day of your borrow period. If doing shipping, your lender will ship your item on day 1 to arrive within day 1-7 and you will ship back on the last day of your borrow period. Simply adjust the borrow period for what time frame works best for you!",
    },
    {
        question: "How do I change my payment information?",
        answer: "This can be done under “Payment methods” in the settings section of the account tab. ",
    },
    {
        question: "Can I cancel a borrow?",
        type: 'list',
        answer: {
            lists: ["If you cancel fourteen (14) or more days in advance of the borrow date, there is no cancellation fee and you will receive a 100% refund issued to the payment method you used for the order.",
                "If you cancel less than fourteen (14) days but more than seven (7) days in adv ",
                "ance of the borrow date, you will receive a refund of 50%.",
                "If you cancel seven (7) or fewer days in advance of the borrow date, you will forfeit 100%.",
            ]
        },
    },
    {
        question: "How do I ship back an item?",
        answer: "On the last day of your borrow period or before, print out your prepaid shipping label under your notifications in the app or in your email. Pack your items in any box or envelope (we recommend reusing old packages!) and affix your printed shipping label. Head to your nearest Canada Post or mailbox to ship out the items.",
    },
    {
        question: "Is there a late fee for shipping back an item?",
        answer: "For every day the item is late to be shipped out, you will be charged $10 which will go to the lender as compensation. If you do not ship back items within 7 days, you will be charged the full cost of the retail value of the item.",
    },
    {
        question: "What if it doesn’t fit or I don’t like the item?",
        answer: "When ordering an item online there is always a risk; many lenders upload pictures of what the item looks like on to mitigate this risk. Return within 24 hours of receiving the item for a full refund (less shipping costs) to use as a credit in the app. Items not shipped back within 24 hours will be charged the full rental price. Items cannot be altered.",
    },
    {
        question: "What if I accidentally ruin the item?",
        answer: "Opt-in for insurance at the time of borrowing which will cover minor wear and tear to the item. If you do not opt-in for insurance, you are liable for 100% of the full cost of the item. ",
    },
    {
        question: "What if I want to buy items right away or once I receive the item?",
        answer: "There is an option to purchase the item on the app if the lender is willing to sell. This can be done before you receive the item or once you receive it.",
    },
    {
        question: "How do I bundle items?",
        answer: "To start bundling items (borrow multiple items from one lender), click add to bundle at the bottom of any listing. Once you are ready to borrow, click “Borrow now” or “Make an offer” to purchase.",
    },
    {
        question: "How do I keep track of my lending / borrow requests? ",
        answer: "Go to “My transactions” under settings in the app.",
    },
];

export const lenderQuestions = [
    {
        question: "How do I list an item / how many items can I list?",
        answer: "Simply click the list button at the bottom, middle of the app screen and begin uploading your item. There are no restrictions on how many items you can list.",
    },
    {
        question: "What items should I list?",
        answer: "High quality and items in great condition - anything from dresses, costumes, full outfits, maternity clothes, children’s clothes etc. ",
    },
    {
        question: "I’m not comfortable doing local pick-ups. What do I do?",
        answer: "It is our priority that everyone feels safe using rax which is why we suggest meeting in a public area. If you are not comfortable with local pick-up, you have the option to choose a shipping only option while creating a listing. Please note this may deter local borrowers who want to avoid shipping costs.",
    },
    {
        question: "Can I cancel a lend?",
        type: 'list',
        answer: {
            lists: ["You may cancel a rental more than seven (7) days before the rental begins with no penalty.",
                "If you cancel within seven (7) days or less of the rental state date, you will be charged a $25 cancellation fee.",
                "If you fail to ship an item on day 1, you will be charged a $50 fee and may be banned from using rax.",
            ]
        },
    },
    {
        question: "How do I price my items?",
        answer: "This is up to the lender’s discretion. The app will recommend charging a 80% discount on items. For longer borrow periods, the app will automatically increase prices.",
    },
    {
        question: "What photos should I upload?",
        answer: "We recommend uploading photos/videos of the item on so borrowers can see what it looks like. Higher quality photos means a higher chance of your time getting borrowed!",
    },
    {
        question: "What if my item gets ruined by the borrower?",
        answer: "rax will assess on a case-by-case basis. Report any damage within 24 hours of receiving the item back. If it’s over 24 hours, we will not be able to assist. Please raise a ticket in the “chat” section of the app and provide full details and photos. For this reason, we don’t suggest lending out items with sentimental value. If it is proven that damage occurred during the rental period, the borrower may have to pay a replacement or damages fee.",
    },
    {
        question: "What if my borrower never ships the item back / is late to ship the item?",
        answer: "In the rare event the borrower does not ship the item back they will be charged the full cost of the item which will be refunded to the lender. For every day the item is late to be shipped out, borrowers will be charged $10 which will go to the lender as compensation.",
    },
    {
        question: "How do I keep track of my upcoming lends?",
        answer: "Please go into settings and the “My transactions” tab.",
    },
    {
        question: "How do I ship out an item?",
        answer: "Lenders will be prompted to ship out the item in the app. A shipping label will be sent to the lender under notifications in the app and to email. Pack your items in any box or envelope and affix your printed shipping label. Head to your nearest Canada Post or mailbox to ship out the items.",
    },
    {
        question: "What if I forget to ship out an item or am late on shipping out an item?",
        answer: "You must ship out the item on day 1 of the borrow period (or before). If you do not ship out the item, your lend will automatically be cancelled and the borrower will receive a full refund. ",
    },
    {
        question: "How do I get paid for lending out an item?",
        answer: "rax uses Stripe to ensure privacy and safety of your information. Simply click “My payouts” in the settings section of the app to redeem. ",
    },
    {
        question: "What if I want to wear my item or am going on vacation & won't be able to send out items?",
        answer: "Just simply make that item or your whole account unavailable for the dates you will be wearing the item/travelling. This can be done for an individual listing under edit or you may pause your account under “Account information” in the settings section.",
    },
]