export const keywords = {
    logout: "Logout",
    settings: "Settings",
    myAddresses: "My addresses",
    paymentMethods: "Payment methods",
    createPaymentMethod: "Create payment method",
    updatePaymentMethod: "Update payment method",
    notifications: "Notifications",
    faq: "FAQ",
    contactUs: "Contact us",
    blockedAccounts: "Blocked accounts",
    myReports: "My reports",
    accountAction: "Account actions",
    pauseAccount: "Pause account",
    unpauseAccount: "Unpause account",
    deleteAccount: "Delete account",
    areYouSureDeletingAccount: "Are you sure you want to delete your account?",
    thisWill: "This will:",
    deleteYourProfile: "Delete your profile",
    deleteAllListing: "Delete all your listings",
    cancelUpcommingLendsBorrows: "Cancel upcoming lends and borrows",
    loseAllAvailableAndFuturePayouts: "You will lose all available and future earnings payouts",
    consider: "Consider ",
    pausing: "pausing",
    accountInstead: " your account instead.",
    deleteMyAccount: "Delete my account",
    keep: "Keep",
    delete: "Delete",
    editPaymentMethod: "Edit payment method",
    deletePaymentMethod: "Delete payment method",
    setAsDefault: "Set as default",
    editAddress: "Edit address",
    deleteAddress: "Delete address",
    allTopics: "All topics",
    general: "General",
    borrowing: "Borrowing",
    lending: "Lending",
    addPaymentMethod: "Add payment method",
    addPayment: "Add payment",
    updatePayment: "Update payment",
    default: "Default",
    pauseAccountMessage: "Pausing your account will make your listings unavailable to borrow. You can reactivate at anytime.",
    howLongWantToPauseAccount: "How long do you want to pause your account?",
    unpauseAccountMessage: 'You can unpause your account at any time by selecting "Unpause account" from settings screen',
    pauseMyAccount: "Pause my account",
    marketingPreferences: "Marketing preferences",
    marketingPrefMessage: "Choose how to get special offers, promos, personalized suggestions and more",
    pushNotification: "Push notifications",
    email: "Email",
    havAQuestion: "Have a question or need support? We’d love to help you out!",
    customerSupport: "Customer Support",
    emailPlaceholder: "info@raxapp.ca",
    socialMediaEmailPlaceholder: "@rent_rax",
    socialMedia: "Social Media",
    instagram: "Instagram",
    tiktok: "Tik Tok",
    unpause: "Unpause",
    close: "Close",
    unpauseMessage1: "By unpausing your account, your listings will once again be available for ",
    unpauseMessage2: ", allowing you to earn money.",
    and: " and ",
    unpauseMessage3: "let's continue where you left off!",
    purchasing: "purchasing",
    addListing: "Add listing",
    home: "Home",
    accountPaused: "Account paused",
    accountUnapused: "Your account is now ",
    unpaused: "Unpaused.",
    unpauseConfirmMessage1: "Your listings are once again be available for ",
    unpauseConfirmMessage2: ", allowing you to earn money",
    namePlaceholder: "Username",
    phonePlaceholder: "Phone number (+1xxxxxxxxxx)",
    emailPlaceholders: "Email address",
    cityPlaceholder: "City",
    countryPlaceholder: "Country",
    lane1Placeholder: "Address",
    lane2Placeholder: "Unit number (if applicable)",
    statePlaceholder: "Province",
    postalCodePlaceholder: "Postal code (M4C5B1)",
    addListingErrorMessage: "Please provide complete information about the item to save the details.",
    yourAccountHasBeenPausedMessage: "Your account has been paused. Listings will be unavailable during this period.",
    youCanUnpauseMessage: "You can unpause your account at any time by selecting settings -> unpause account",
    version: "Version",
    minorVersion: "Minor version",
    unblock: 'Unblock',
    restricts: "Restrict",
    unrestricts: "Unrestrict",
};


export const dummyData = [
    { id: 1, name: 'John Doe', location: "Toronto, Canada", image: 'https://picsum.photos/seed/john/150', listings: 15, size: "M", price: '$150' },
    { id: 2, name: 'Jane Smith', location: "Vancouver, Canada", image: 'https://picsum.photos/seed/jane/150', listings: 25, size: "L", price: '$300' },
    { id: 3, name: 'Alice Johnson', location: "Montreal, Canada", image: 'https://picsum.photos/seed/alice/150', listings: 35, size: "XL", price: '$250' },
    { id: 4, name: 'Bob Brown', location: "Calgary, Canada", image: 'https://picsum.photos/seed/bob/150', listings: 20, size: "S", price: '$180' },
    { id: 5, name: 'Charlie Davis', location: "Ottawa, Canada", image: 'https://picsum.photos/seed/charlie/150', listings: 10, size: "M", price: '$120' },
    { id: 6, name: 'Emily Evans', location: "Edmonton, Canada", image: 'https://picsum.photos/seed/emily/150', listings: 50, size: "L", price: '$400' },
    { id: 7, name: 'Franklin Moore', location: "Winnipeg, Canada", image: 'https://picsum.photos/seed/franklin/150', listings: 30, size: "S", price: '$200' },
    { id: 8, name: 'Grace Thomas', location: "Halifax, Canada", image: 'https://picsum.photos/seed/grace/150', listings: 40, size: "XL", price: '$350' },
    { id: 9, name: 'Henry Wilson', location: "Quebec City, Canada", image: 'https://picsum.photos/seed/henry/150', listings: 18, size: "M", price: '$170' },
    { id: 10, name: 'Ivy Martinez', location: "Hamilton, Canada", image: 'https://picsum.photos/seed/ivy/150', listings: 22, size: "L", price: '$280' },
    { id: 11, name: 'Jack White', location: "London, Canada", image: 'https://picsum.photos/seed/jack/150', listings: 45, size: "XL", price: '$320' }
];
