export const keywords = {
    myAddresses: "My addresses",
    addressInfo: "Address info",
    addAddress: "Add address",
    editAddress: "Edit address",
    addAnAddress: "Add an address",
    setAsDefault: "Set as default",
    deleteAddress: "Delete address",
    default: "Default",
    updatedDefaultAddress: "changed default address successfully",
    postalCode: "Postal code",
    postalCodePlaceholder: "M4C5B1",
    apprtmentSuit: 'Apartment/Suite',
    city: "City",
    cityPlaceholder: "Cty",
    state: "State",
    statePlaceholder: "Province",
    deliveryHandOffIntruction: 'Delivery/Hand-off instructions',
    apprtmentSuitPlaceholder: 'eg Unit-4',
    deliveryHandOffIntructionPlaceholder: 'Leave on front porch',
    save: "Save",
    saveAddress: "Save address",
    invalidPostalCode: "Invalid postal code",
}