export const keywords = {
    addListing: "Add a listing",
    addPhotoVideo: "Add photos/video",
    selectCoverPhoto: "Select cover photo first",
    addFrontImage: "Select front image",
    addBackImage: "Select back image",
    photos: "Photos",
    videos: "Videos",
    brandName: "Brand name",
    nameOfItem: "Name of item",
    descriptionPlaceholder: "Description (Condition, material, fit, etc)",
    category: "Category",
    subCategory: "Sub-category",
    microCategory: "Micro-category",
    occasion: "Occasion",
    size: "Size",
    color: "Color",
    fit: "Fit",
    length: "Length",
    condition: "Condition",
    location: "Location",
    address: "Address",
    pricing: "Pricing",
    retailPricePlaceholder: "Retail price (include taxes, shipping, duties)",
    listingPricePlaceholder: "Listing price (include dry cleaning costs if applicable)",
    recommendListingPriceMessage: "We recommend the listing price to be 20% of retail price",
    sellYourListing: "Sell your listing",
    sellPrice: "Sell price",
    sellRecommendedLisitngPriceMessage: "We recommend the listing price to be 50% of retail price",
    getPaidOut: "Get paid out",
    connectBankAccount: "Connect bank account",
    bankAccountMessage: "Connect bank account details to get paid for your lends.",
    note: "Note: ",
    availibility: "Availability",
    selectLendPeriod: "Select period to lend it out",
    unavaialableDate: "Select unavailable dates",
    tight: "Tight",
    perfect: "Perfect",
    loose: "Loose",
    short: "Short",
    long: "Long",
    bad: "Bad",
    good: "Good",
    great: "Great",
    saveItem: 'Save item',
    updateItem: "Update item",
    addAddress: "Add new address",
    chooseOccation: "Choose occasion",
    chooseCategory: "Choose category",
    chooseSubCategory: "Choose sub-category",
    chooseMicroCategory: "Choose micro-category",
    selectPriod: "Select period",
    selectAppApply: "Please select all that apply",
    selectSize: "Select size",
    selectColor: "Select colour",
    videoToastMessage: "You already selected Video",
    imageToastMessage: "You already selected 5 images",
    maximumReachToastMessage: "maximum allowed file reached",
    default: "Default",
    addBankAccount: "Add bank account",
    enterAddressInformation: "Enter Address Information",
    addBankAccountMessage: 'please add at least 1 bank account',
    countryPlaceholder: "Country code",
    currencyPlaceholder: "Currency",
    routingPlaceholder: "Transit number (11000)",
    bankPlaceholder: "Bank (000)",
    accountNumberPlaceholder: "Bank number (000123456789)",//"Account number",
    dobPlaceholder: "Birth Date",
    addressPlaceholder: "Address",
    statePlaceholder: "Province",
    phoneNumberPlaceholder: "Phone number (+1xxxxxxxxxx)",
    filePlaceholder: "Upload identity document",
    postalCodePlaceholder: "Postal code (M4C5B1)",
    cityPlaceholder: "City",
    namePlaceholder: "bank account",//"Account title",
    typePlaceholder: "Account type",
    setAsDefault: "Set as default",
    editBankAccount: "Edit bank account",
    deleteBankAccount: "Delete bank account",
    bankAccounts: "Bank accounts",
    fillAllFieldMessage: 'please fill all fields',
    selectImageMessage: 'please select at least 1 image for your listing.',
    addListingErrorMessage: "Please provide complete information about the item to save the details.",
    continue: "Continue",
    addDocumentMessage: "Upload Government-Issued ID",
    addAdditionalDocumentMessage: "Upload Proof of Liveness:",
    uploadDocument: "Upload document",
    uploadDocumentInstructions: "To verify your identity, please upload both the front and back of your Government-issued ID. Each side should be fully visible in the photos.\n\nImportant Notes:\n\u2022 Accepted ID: Includes National ID card or any other valid Government-issued ID.\n\u2022 Front Side: Ensure all details such as your name, photo, and ID number are clearly visible.\n\u2022 Back Side: Ensure all details such as any additional information or security features are clearly visible.\n\u2022 Legibility: Both sides of the ID should be clear and easy to read, with no glare or shadows.\n\u2022 Acceptable Formats: JPG, PNG\n\u2022 Maximum File Size: 5 MB (per side)",
    uploadAdditionalDocumentInstructions: "To verify your identity, please upload a clear image of yourself holding your Government-issued ID.\n\nImportant Notes:\n\u2022 Face the Camera: Ensure your face is clearly visible and centered in the image.\n\u2022 Hold Your ID: Hold your Government-issued ID next to your face so that both your face and the ID are fully visible.\n\u2022 Legibility: Make sure that all details on the ID (e.g., name, photo, ID number) are clearly legible in the image.\n\u2022 Good Lighting: Take the photo in a well-lit environment to avoid shadows on your face and ID.\n\u2022 No Obstructions: Ensure there are no accessories like hats or glasses that might obstruct your face.\n\u2022 Acceptable Formats: JPG, PNG\n\u2022 Maximum File Size: 5 MB",
    company: "Company",
    individual: "Individual",
    addBankInformation: "Add bank information",
    frontImage: "Front side image",
    backImage: "Back side image",
};

export const fits: ('Tight' | 'Perfect' | 'Loose')[] = [
    "Tight",
    "Perfect",
    "Loose"
];

export const lengths: ('Short' | 'Perfect' | 'Long')[] = [
    "Short",
    "Perfect",
    "Long"
];

export const conditions: ('Bad' | 'Good' | 'Great')[] = [
    "Bad",
    "Good",
    "Great"
];

export const days = [
    { text: '4 Days', days: 4, value: 0 },
    { text: '10 Days', days: 10, value: 1 },
    { text: '20 Days', days: 20, value: 2 },
    { text: '1 Month', days: 30, value: 3 },
    { text: '3 Month', days: 90, value: 4 },
    { text: '6 Month', days: 180, value: 5 },
]

export const occasions = [
    // { text: 'Formal', },
    // { text: 'Work' },
    // { text: 'Vocation' },
    // { text: 'Wedding' },
    // { text: "Prom" },
    // { text: 'Festival' },
    { text: 'Wedding guest', },
    { text: 'Birthday' },
    { text: 'Night out' },
    { text: 'New years' },
    { text: "Thanksgiving" },
    { text: 'Easter' },
    { text: 'Valentine\'s Day', },
    { text: 'Halloween' },
    { text: 'Holiday' },
    { text: 'Bridal' },
]

export const colors = [
    { text: 'Multicoloured (neutral)' },
    { text: 'Multicoloured (bright)' },
    { text: "Green" },
    { text: "White" },
    { text: "Black" },
    { text: 'Yellow' },
    { text: 'Navy' },
    { text: "Pink" },
    { text: 'Orange' },
    { text: 'Brown' },
    { text: 'Purple', },
    { text: 'Red' },
    { text: 'Blue' },
    { text: 'Gold' },
    { text: "Silver" },
]

export const sizes = [
    { text: 0, },
    { text: 2 },
    { text: 4 },
    { text: 6 },
    { text: 8 },
    { text: 10 },
]

export const categories = [
    { text: 'Men', },
    { text: 'Women' },
    { text: 'Children' },
    { text: "Maternity" },
]

export const subCategories = [
    { text: 'Accessories', },
    { text: 'Bags' },
    { text: 'Dresses' },
    { text: 'Full Outfits' },
    { text: "Jacket & Coats" },
    { text: 'jean' },
]

export const states = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'NT', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT'];
