export const keywords = {
    noOrder: "No orders yet!",
    noOrderMessage: "Start browsing our 500+ listings and find your next look.",
    browseSelections: "Browse listings",
    searchPlaceholder: 'Search my transactions',
    requests: "Requests",
    activeOrder: "Active Orders",
    completedOrder: "Completed Orders",
    cancelledOrder: "Cancelled Orders",
    item: "Item: ",
    requestExpireInfo: "This request expires in 24:00:00",
    borrowerInfo: "Borrower info",
    buyerInfo: "Buyer info",
    awayMessage: " kms from current location",
    memberOnRax: "Member on rax since",
    itemborrowed: "Items borrowed",
    rating: "Rating",
    reviewsByLender: "Reviews by lenders",
    borrowDate: "Borrow dates",
    buyDate: "Buy dates",
    borrowMethod: "Borrow method",
    buyMethod: "Buy method",
    earnings: "Earnings",
    accept: "Accept",
    deny: "Deny",
    meetUpDate: "Local pick-up date",
    shipDate: "Ship date",
    startDate: "Start Date",
    endDate: "End date",
    totalAmount: "Total amount",
    borrowPeiod: "Borrow period",
    borrower: "Borrower",
    seller: "Seller",
    buyer: "Buyer",
    trackingNumber: "Tracking Number",
    whatIneedToDo: "What do I need to do next?",
    nextSteps: "Next steps",
    shipWithCanadaPost: "Ship with Canada Post",
    downloadShippingLabel: "Download shipping label",
    downloadShippingBackLabel: "Download shipping back label",
    days: "days",
    whenItemShipBack: "(for when the item is shipped back)",
    howWasBorrower: "How was the borrower?",
    howWasBuyer: "How was the buyer?",
    reviewBorrower: "Review borrower",
    reviewBuyer: "Review buyer",
    needHelpWithItem: "Need help with your item?",
    contactSupport: "Contact Support",
    faqs: "FAQs",
    lender: "Lender",
    cancelBorrow: "Cancel Borrow",
    rentAgain: "Rent again",
    howWasItem: "How was the item?",
    reviewItem: "Review item",
    getRefund: "Get a refund",
    gotIt: "Got it",
    getPaidOut: "Get paid out",
    firstSellCongraulationMessage: "Congratulations on selling your item with rax. Here are the next steps to follow for a smooth sell experience!",
    firstBuyCongratulationMessage: "Congratulations on buying your item with rax. Here are the next steps to follow for a smooth buy experience!",
    firstLendCongratulationMessage: "Congratulations on your lend with rax. Here are the next steps to follow for a smooth lending experience!",
    firstBorrowCongratulationMessage: "Congratulations on your borrow with rax. Here are the next steps to follow for a smooth borrow experience!",
    noBackAccountMessage: "You do not have a bank account on file. To get paid out, please add a bank account",
    addAccount: "Add account",
    totalEarning: "Total earnings",
    availablePayout: "Available payout",
    futurePayout: "Future payout",
    backAccount: "Bank account",
    noBankAccount: "No bank account added",
    pendingPayout: "Pending payouts",
    pendingLayoutMessage: "You are able to redeem payouts 2 days after the local borrow period and 7 days after the shipping borrow period.",
    noPayoutMessage: "No payouts yet! Start by lending out or selling items.",
    addlisting: "Add listing",
    borrowedBy: "Borrowed by ",
    purchaseBy: "Purchased by ",
    total: "Total",
    selectItem: "Select the items that you want to get paid out for",
    congratulations: "Congratulations",
    yourMoneyOnTheWay: "Your money is on its way to your bank account.",
    summary: "Summary",
    accountEnding: "Account ending in xxxx-",
    estimatedTimeOfArrival: "Estimated time of arrival",
    businessDays: "3-5 bussiness days",
    getPaidOutForOtherItems: "Get paid out for other items",
    returnHome: "Return home",
    review: "Review",
    howYouRateBorrower: "How would you rate the borrower?",
    addPhotoOrVideo: "Add photo or video",
    titleOfReview: "Titile of your review",
    titleReviewPlaceholder: "What\'s most important to know?",
    writeReview: "Write your review",
    reviewPlaceholder: "How was the condition of the item when you got it back? How was the borrower?",
    submit: "Submit",
    buy: "Buy",
    borrow: "Borrow",
    lend: "Lend",
    sell: "Sell",
    denyStatus: "decline",
    status: {
        completed: "complete",
        inProgress: "in progress",
        paidOut: 'paid out',
        decline: "decline",
    },
    leaveNotePlaceholder: "(optional) Leave a note for the borrower",
    leaveSellerNotePlaceholder: "(optional) Leave a note for the buyer",
    note: "Note: ",
    noteMessageYourMessageWillBeSent: "Your message will be sent after you make a decision for the request",
    lstingFrom: "Listing From",
    localPickup: "Local pickup",
    shipping: "Shipping",
    addReviewError: "Please write title and description first",
    emptyImageError: "Image or video is required",
    confirmAdress: "Confirm your address",
    updateAddress: "Update address",
    looksGood: "Looks good!",
    update: "Update",
    back: "Back",
    save: "Save",
    waitingForBorrowerToReview: "Waiting for borrower to review",
    waitingForBuyerToReview: "Waiting for buyer to review",
    yourAddress: "Your address",
    addressUpdated: "Address updated",
    yourCurrentAddress: "Your current address is ",
    yourUpdatedAddress: "Your updated address is ",
    updatedAddressMessage: "The borrower will have 24 hours to accept the change, update or cancel their order.",
    edit: "edit",
    buyFor: "Buy for ",
    addressUpdate: "Address update",
    lookGood: "Looks good",
    distanceToNewAddress: "Distance to new address",
    originalBorrowMethod: "Original borrow method",
    shippingCost: "Shipping cost",
    newShippingCost: "New shipping cost",
    newTotalAmount: "New total amount",
    yourLenderJustUpdatedAddress: "Your lender just updated the address on this borrow. ",
    newAddressForLocalPickup: "New address for local pick up is now distance km away from ",
    pleaseConfirm: "Please confirm you would still like to do local pick-up for free, or switch to shipping",
    pleaseConfirmMessage: "Please confirm you would still like to do local pick-up for free, or switch to shipping for a fee.",
    requestExpires: "Review order request expires in 24:00:00",
    cancelOrder: "Cancel order",
    estimatedShipppingCost: "Estimated shipping cost",
    orderCancelled: "Order cancelled",
    orderUpdated: "Address confirmed",
    browseOtherListings: "Browse other listings",
    orderConfirmed: "Order confirmed",
    cancelled: "Cancelled",
    allow: "Allow",
    allowLocationMessage: "Allow location permission to see how far away items are from you.",
    addressPlaceholder: "Enter address manually",
    orderDetails: "Order Details",
    payout: "Payout",
    noLinkedAccountMessage: "Add a bank account",
    chatWithLender: "Chat with lender",
    chatWithSeller: "Chat with seller",
    noPostalCode: "Postal code not exist, choose a different address",
    meetupOn: 'Meet up on',
    shipOn: "Ship on",
    messageFromBorrower: "Message from the borrower",
    messageFromBuyer: "Message from the buyer",
    reply: "Reply",
    shippingDetail: "Shipping detail",
    track: "Track",
    service: "Service",
    destination: "Destination",
    expectedDelivery: "Expected delivery",
    updatedDelivery: "Updated delivery",
    location: "Location",
    time: "Time",
    delayReason: "Reason for delay",
    latestUpdates: 'Latest updates',
}

export const stepsToLendShipping = [
    { step: "Print off the shipping label and add it onto the box" },
    { step: "Print off the back shipping label and add it into the box for the borrower to ship the item back to you" },
    { step: "On fixedDate, bring it to your nearest Canada Post" },
    { step: "Your item will be shipped back to you on fixedDate" },
    { step: "Ensure to clean the item before lending it out again!" },
]


export const stepsToLendLocalPickLender = [
    { step: "Message the borrower in the chat section of the app to decide on the time and place to meet up" },
    { step: "Meet up and hand off the item on fixedDate" },
    { step: "Pick up the item back from the borrower on fixedDate" },
    { step: "Review the borrower so other lenders feel comfortable lending to them!" },
    { step: "Ensure to clean the item before lending it out again!" },
]

export const stepsToBuyFromLocalPicker = [
    { step: "Message the seller in the chat section of the app to decide on the time and place to meet up" },
    { step: "Meet up and receive the item on fixedDate" },
    { step: "Wear the item & be sure to tag <b>@rent_rax!</b>" },
    { step: "Be sure to revew the item and your experience with the seller!" },
]

export const stepsToBuyFromShipping = [
    { step: "Your item will be shipped to you on fixedDate. Track estimated delivery data using the tracking number" },
    { step: "Wear the item & be sure to tag <b>@rent_rax!</b>" },
    { step: "Be sure to revew the item and your experience with the seller!" },
]

export const stepsToSellThroughShipping = [
    { step: "Print off the shipping label and add it onto the box" },
    { step: "On fixedDate, bring it to your nearest Canada Post and ship it" },
    { step: "Review your experience with the buyer" },
]

export const stepsToSellThroughLocalPickup = [
    { step: "Message the buyer in the chat section of the app to decide on the time and place to meet up" },
    { step: "Meet up and hand off the item on fixedDate" },
    { step: "Review your experience with the buyer" },
]

export const stepsToBorrowLocalPickLender = [
    { step: "Message the lender in the chat section of the app to decide on the time and place to meet up" },
    { step: "Meet up and Pick up the item on fixedDate" },
    { step: "Wear the item! Make sure to tag @rent_rax!" },
    { step: "Drop off the item on fixedDate" },
    { step: "Review the item so other borrowers have an idea of fit and quality!" },
]

export const stepsToBorrowShipping = [
    { step: "Your item will be shipped to you on fixedDate. Track estimated delivery data using the tracking number" },
    { step: "Wear the item & be sure to tag <b>@rent_rax!</b>" },
    { step: 'On fixedDate, print out the back shipping label (or the label if the lender included it in the box)' },
    { step: "Be sure to revew the item and your experience with the seller!" },
]

export const listingFilters = ["All", 'Last 7 days', 'Last month', 'Last 3 months'];

export const placeholderPicture = 'https://hrnylgxecwjrlbnqbodg.supabase.co/storage/v1/object/public/avatars/placeholder-avatar.jpg?t=2024-03-20T00%3A41%3A49.189Z';
