import { StyleSheet } from "react-native";

export const SSF = StyleSheet.create({
  innerComponents: {
    width: '45%',
    paddingTop: 5,
    paddingLeft: 1,
    gap: 16,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  headerText: {
    fontSize: 24,
    fontWeight: '700',
    color: 'rgba(0, 0, 0, 1)',
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  Description: {
    width: '100%',
    height: 75,
    paddingLeft: 12,
  },
  descriptionText: {
    fontSize: 12,
    fontWeight: '400',
    color: 'rgba(51, 51, 51, 1)',
    lineHeight: 20,
    marginTop: 5,
    letterSpacing: 0.5,
  },
  inputContainer: {
    width: '100%',
    height: 690,
    gap: 18,
    alignSelf: 'center',
    alignItems: 'center',
    paddingTop: 8,
    paddingLeft: 10,
  },
  innerContainer: {
    width: '98%',
    gap: 2,
    alignSelf: 'center',
    paddingTop: 8,
    paddingLeft: 0,
  },
  innerContainer2: {
    width: '98%',
    alignSelf: 'center',
    paddingTop: 10,
    paddingLeft: 5,
  },

  custInp: {
    width: '100%',
    height: 45,
    gap: 6,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 0,
    paddingLeft: 0,
    borderBottomWidth: 0.6,
    borderColor: 'lightgray',
  },
  TextComponent: {
    width: '80%',
    height: 55,
    gap: 6,
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 15,
    paddingLeft: 0,
    borderColor: 'lightgray',
  },
  text: {
    fontSize: 16,
    fontWeight: '400',
    color: 'rgba(51, 51, 51, 1)',
    lineHeight: 24,
    letterSpacing: 0.5,
  },

  ImageComponent: {
    width: '15%',
    height: 55,
    gap: 6,
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    paddingTop: 10,
    paddingLeft: 22,
    borderColor: 'lightgray',
  },
  CustomText: {
    fontSize: 16,
    fontWeight: '700',
    color: 'rgba(51, 51, 51, 1)',
    lineHeight: 24,
    letterSpacing: 0.5,
  },
});