export const keywords = {
    chats: "Chats",
    noChat: "No new chats! Receive messages here or send a message to other rax users.",
    message: "Message",
    block: "Block",
    unblock: "Unblock",
    report: "Report",
    restrict: "Restrict",
    unrestrict: "Unrestrict",
    blockAndReport: "Block & Report",
    submit: "Submit",
    delete: "Delete",
    reasonToReportAccount: "What is the reason for reporting this account?",
    reasonPlaceholder: "Tell us the reason for reporting this account...",
    reportMessage: "Thank you for your report. We\'ve received your feedback and will review it promtly.",
    unblockMessage: " has been unblocked succcessfully.",
    deletedMessages: "Sucessfully deleted all messages with ",
    blockMessage :" has been bloked. Your can see other accounts in settings",
    restrictMessage: "Restricted post, it will not be visible to you",
    unrestrictMessage: "Unrestricted post, it will be visible to you",
    thanksWeReceivedYourReport: "Thank you, we have received your report!",
    youCanBlock: "You can also Block",
    theyWouldNotAbleToSendMessage: "They would not be able to message you or find you on rax",
    theirListingWontShow: "Their listings won\'t show up for you anymore",
    youCanUnblock: "You can unblock them anytime from ",
    settingsBlockedAccounts: "Settings>Blocked accounts",
}